# Generated by Django 3.2.4 on 2021-06-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.IntegerField(verbose_name='Número da nota')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produtos')),
            ],
            options={
                'verbose_name': 'Nota de Saida',
                'verbose_name_plural': 'Notas de Saida',
                'ordering': ['-produto'],
            },
        ),
    ]
